services:
  # Spring Boot Backend
  - type: web
    name: ping-backend
    env: java
    region: singapore
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/ping-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: ping-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: NAVER_SMS_ACCESS_KEY
        sync: false
      - key: NAVER_SMS_SECRET_KEY
        sync: false
      - key: NAVER_SMS_SERVICE_ID
        sync: false
      - key: NAVER_SMS_FROM_NUMBER
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://ping-sos.onrender.com

databases:
  - name: ping-postgres
    databaseName: ping_production
    user: ping_user
    plan: free